---
driver:
  name: vagrant
  network:
    - ["forwarded_port", {guest: 5555, host: 5555}]

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.10

suites:
  - name: default
    run_list:
      - recipe[messaging_server::default]
    attributes:
